export enum ClearMode {
  SCREEN = 'SCREEN',
  FROM_CURSOR_TO_EOL = 'FROM_CURSOR_TO_EOL',
  ALL_AFTER_CURSOR = 'ALL_AFTER_CURSOR',
  ALL_BEFORE_CURSOR = 'ALL_BEFORE_CURSOR',
  FROM_LINE_START_TO_CURSOR = 'FROM_LINE_START_TO_CURSOR',
  LINE = 'LINE',
  STATUS_LINE = 'STATUS_LINE',
  SCREEN_AND_STATUS_LINE = 'SCREEN_AND_STATUS_LINE',
}